### ISSUE TITLE
feat: User 관련 구현 내용

### ISSUE THREAD

**Issue by sooooooongyi** [wjdtjsah12/DeliveryMiniProject#29]
### User 작업 내역
- user entity 구현
- user service 구현
- user repository 구현
- user dto 구현
- spring security 적용
  - 인증/인가 필터 구현
  - JWT 유틸리티 클래스 구현
- signup 사용자 입력에 대한 validation 설정

### User 테이블 상세
![스크린샷 2024-11-12 오후 4 16 38](https://github.com/user-attachments/assets/8195f54c-f975-4524-af18-8c35e14fbd21)
```
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(nullable = false)
  private String username;

  @Column(nullable = false)
  private String password;

  @Column(nullable = false)
  @Enumerated(value = EnumType.STRING)
  @Setter
  private UserRoleEnum role;
```
- created_by, created_at, updated_by, updated_at, is_deleted 등의 값은 BaseEntity에서 관리됩니다.

### User 관련 API
- 자세한 API 문서는 [링크](https://www.notion.so/teamsparta/26-S-A-c91495224b444024a68a65ed4b92223c)에서 확인할 수 있습니다.
#### 1. [POST] /api/users/signup
- 유저이름(ID)과 비밀번호를 입력받아 회원을 등록합니다.
#### 2. [POST] /api/users/signin
- 유저이름(ID)과 비밀번호를 입력받아 로그인합니다.
### 3. [GET] /api/users/info
- 현재 인증/인가된 회원의 이름과 권한을 출력합니다.
#### 4. [POST] /api/users/role/{role}
- 회원의 권한을 수정합니다.
- 수정할 수 있는 권한은 "CUSTOMER", "OWNER", "MANAGER", "MASTER" 입니다.

**Comment by wjdtjsah12** [comment]
고생 많으셨습니다. 해당 이슈 해결된걸로 파악되어서 닫도록 하겠습니다!
